{% set name = "mattflow" %}
{% set version = "1.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/ThanasisMattas/mattflow.git

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - mattflow=mattflow.__main__:main
  include_recipe: False

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click >=7.0
    - numpy >=1.18.5
    - matplotlib >=3.3.1
    - joblib >=0.13.2
    - numba >=0.51.2

about:
  home: https://github.com/ThanasisMattas/mattflow.git
  license: GNU General Public License v3 or later (LGPLv3+)
  license_family: LGPL
  license_file: COPYING
  summary: A CFD python package for the Shallow Water Equations

extra:
  maintainers:
    - ThanasisMattas